/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De3;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASM
 */
public class Quanlynhanvien extends javax.swing.JFrame {
    ArrayList<Nhavien> listNhanVien=new ArrayList<>();
    /**
     * Creates new form Quanlynhanvien
     */
    public Quanlynhanvien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jf_hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jf_ngaysinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jf_diachi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jf_gioitinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jf_phongban = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jf_hesoluong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jf_thamnien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jf_luongcoban = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ja_hienthi = new javax.swing.JTextArea();
        b_themmotnhanvien = new javax.swing.JButton();
        b_luudanhsachnhavien = new javax.swing.JButton();
        b_modanhsachnhanvien = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        b_xemdanhsachnhavien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Ngày sinh:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Phòng ban:");

        jLabel7.setText("Hệ số lương:");

        jLabel8.setText("Thâm niên:");

        jLabel9.setText("Lương cơ bản:");

        ja_hienthi.setColumns(20);
        ja_hienthi.setRows(5);
        jScrollPane1.setViewportView(ja_hienthi);

        b_themmotnhanvien.setText("Thêm một nhân viên");
        b_themmotnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themmotnhanvienActionPerformed(evt);
            }
        });

        b_luudanhsachnhavien.setText("Lưu danh sách nhan viên");
        b_luudanhsachnhavien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_luudanhsachnhavienActionPerformed(evt);
            }
        });

        b_modanhsachnhanvien.setText("Mở danh sách nhân viên");
        b_modanhsachnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modanhsachnhanvienActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        b_xemdanhsachnhavien.setText("Xem danh sách nhân viên");
        b_xemdanhsachnhavien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemdanhsachnhavienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jf_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jf_hesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b_xemdanhsachnhavien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_themmotnhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jf_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(b_luudanhsachnhavien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_modanhsachnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jf_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jf_hesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jf_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jf_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_themmotnhanvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_xemdanhsachnhavien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_luudanhsachnhavien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_modanhsachnhanvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void b_themmotnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themmotnhanvienActionPerformed
        // TODO add your handling code here:
        try {
            String a=jf_hoten.getText();
            String b=jf_ngaysinh.getText();
            String c=jf_diachi.getText();
            String d=jf_gioitinh.getText();
            String e=jf_phongban.getText();
            double f=Double.parseDouble(jf_hesoluong.getText());
            double g=Double.parseDouble(jf_thamnien.getText());
            double h=Double.parseDouble(jf_luongcoban.getText());
            Nhavien nv=new Nhavien(a, b, c, d, e, f, g, h);
            listNhanVien.add(nv);
            jf_hoten.setText("");
            jf_ngaysinh.setText("");
            jf_diachi.setText("");
            jf_gioitinh.setText("");
            jf_phongban.setText("");
            jf_hesoluong.setText("");
            jf_thamnien.setText("");
            jf_luongcoban.setText("");
            JOptionPane.showMessageDialog(null,"Thêm một sinh viên thành công!","!!!Thông báo!!!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Thêm một sinh viên không thành công!","!!!Thông báo!!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_themmotnhanvienActionPerformed

    private void b_luudanhsachnhavienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_luudanhsachnhavienActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter fw=new FileWriter("nhavien.dat");
            BufferedWriter bw=new BufferedWriter(fw);
            for (Nhavien nv: listNhanVien)
            {
                bw.append("\n"+nv.getHoten()+"$"+nv.getNgaysinh()+"$"+nv.getDiachi()+"$"+nv.getGioitinh()+"$"+nv.getPhongban()+"$"+nv.getHesoluong()+"$"+nv.getThamnien()+"$"+nv.getLuongcoban()+"$"+nv.luongthucling());
            }
            JOptionPane.showConfirmDialog(null,"Lưu danh sách nhân viên thành công","Thông báo!!!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Lưu danh sách nhân viên không thành công.","Thông báo!!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_luudanhsachnhavienActionPerformed

    private void b_modanhsachnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modanhsachnhanvienActionPerformed
        // TODO add your handling code here:
        try {
            List<String> listNV = Files.readAllLines(Paths.get("nhavien.dat"));
            for(String l: listNV)
            {
                String[] parts = l.split("\\$");
                Nhavien nv=new Nhavien(parts[0],parts[1],parts[2],parts[3],parts[4],Double.parseDouble(parts[5]),Double.parseDouble(parts[6]),Double.parseDouble(parts[7]));
                listNhanVien.add(nv);
            }
            JOptionPane.showMessageDialog(null,"Mở danh sách nhân viên thành công.","thông báo!!!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Mở danh sách nhân viên không thành công.","thông báo!!!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_modanhsachnhanvienActionPerformed

    private void b_xemdanhsachnhavienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemdanhsachnhavienActionPerformed
        // TODO add your handling code here:
        for (Nhavien nv: listNhanVien)
        {
            ja_hienthi.append(nv.toString());
        }
    }//GEN-LAST:event_b_xemdanhsachnhavienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlynhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_luudanhsachnhavien;
    private javax.swing.JButton b_modanhsachnhanvien;
    private javax.swing.JButton b_themmotnhanvien;
    private javax.swing.JButton b_xemdanhsachnhavien;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ja_hienthi;
    private javax.swing.JTextField jf_diachi;
    private javax.swing.JTextField jf_gioitinh;
    private javax.swing.JTextField jf_hesoluong;
    private javax.swing.JTextField jf_hoten;
    private javax.swing.JTextField jf_luongcoban;
    private javax.swing.JTextField jf_ngaysinh;
    private javax.swing.JTextField jf_phongban;
    private javax.swing.JTextField jf_thamnien;
    // End of variables declaration//GEN-END:variables
}
