/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De6;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author ASM
 */
public class Dictionary extends javax.swing.JFrame {
    ArrayList<Word> listWord=new ArrayList<>();
    public void input ()
    {
        Word w1=new Word("01", "angel", "Thiên Thần");
        listWord.add(w1);
        Word w2=new Word("02", "boss", "Ông chủ");
        listWord.add(w2);
        Word w3=new Word("03", "car", "Ô tô");
        listWord.add(w3);
        Word w4=new Word("04", "dad", "Bố");
        listWord.add(w4);
        Word w5=new Word("05", "egg", "Trứng");
        listWord.add(w5);
        Word w6=new Word("06", "fly", "Bay");
        listWord.add(w6);
        Word w7=new Word("07", "good", "tốt");
        listWord.add(w7);
        Word w8=new Word("08", "hi", "Xin chào");
        listWord.add(w8);
        Word w9=new Word("09", "i", "Tôi");
        listWord.add(w9);
        Word w10=new Word("10", "key", "chìa khóa.");
        listWord.add(w10);
        Collections.sort(listWord,new sortbyen());
        
        
    }
    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jf_tucantim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jf_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jf_en = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jf_vn = new javax.swing.JTextField();
        b_tratudien = new javax.swing.JButton();
        b_tratudien1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ja_hienthi = new javax.swing.JTextArea();
        b_themtu = new javax.swing.JButton();
        b_themtumoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Tra từ điển");

        jLabel2.setText("Từ cần tìm:");

        jLabel3.setText("ID:");

        jLabel4.setText("EN:");

        jLabel5.setText("VN:");

        b_tratudien.setText("Tra từ điển");
        b_tratudien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tratudienActionPerformed(evt);
            }
        });

        b_tratudien1.setText("Exit");
        b_tratudien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tratudien1ActionPerformed(evt);
            }
        });

        ja_hienthi.setColumns(20);
        ja_hienthi.setRows(5);
        jScrollPane1.setViewportView(ja_hienthi);

        b_themtu.setText("Thêm 10 từ mạc định vào list");
        b_themtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themtuActionPerformed(evt);
            }
        });

        b_themtumoi.setText("Thêm từ mới");
        b_themtumoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themtumoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(353, 353, 353))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_tratudien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_tratudien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_tucantim, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jf_en, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jf_vn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(b_themtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_themtumoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jf_tucantim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jf_en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jf_vn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_tratudien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_themtumoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_themtu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_tratudien1)
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_tratudien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tratudien1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_tratudien1ActionPerformed

    private void b_tratudienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tratudienActionPerformed
        // TODO add your handling code here:
        
        int dau=0,cuoi=listWord.size(),giua;
        String test="",x=jf_tucantim.getText(),y="";
        do
        {
            giua=(dau+cuoi)/2;
            test=listWord.get(giua).getEn();
            if (x.compareTo(test)==0)
            {
                y=listWord.get(giua).getVn();
                break;
            }
            else if(x.compareTo(test)>0)
                dau=giua;
            else
                cuoi=giua;
        }while ((cuoi-dau)!=1);
        if (y=="")
        {
            JOptionPane.showMessageDialog(null,"Không tim thấy từ mới bạn phải bổ sung từ này vào tìm kiếm.","Thông báo.",JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            ja_hienthi.append("\n=========================================================\nKết quả tìm kiếm: "+y);
        }
    }//GEN-LAST:event_b_tratudienActionPerformed

    private void b_themtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themtuActionPerformed
        // TODO add your handling code here:
        try {
            input();
            JOptionPane.showMessageDialog(null,"Thêm 10 từ thành công.","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Thêm 10 từ không thành công.","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_themtuActionPerformed

    private void b_themtumoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themtumoiActionPerformed
        // TODO add your handling code here:
        try {
            String a=jf_id.getText();
            String b=jf_en.getText();
            String c=jf_vn.getText();
            Word w=new Word(a, b, c);
            listWord.add(w);
            Collections.sort(listWord,new sortbyen());
            JOptionPane.showMessageDialog(null,"Thêm từ mới thành công","Thông báo!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Xẩy ra lỗi khi thêm từ.","Thong báo!",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_b_themtumoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_themtu;
    private javax.swing.JButton b_themtumoi;
    private javax.swing.JButton b_tratudien;
    private javax.swing.JButton b_tratudien1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ja_hienthi;
    private javax.swing.JTextField jf_en;
    private javax.swing.JTextField jf_id;
    private javax.swing.JTextField jf_tucantim;
    private javax.swing.JTextField jf_vn;
    // End of variables declaration//GEN-END:variables
}
