/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai3;

/**
 *
 * @author ASM
 */
import java.util.ArrayList;
public class Quanlygiaodich extends javax.swing.JFrame {
    private ArrayList<Vang> listVang=new ArrayList();
    private ArrayList<Tiente> listTiente=new ArrayList();
    Manager m=new Manager();
    /**
     * Creates new form Quanlygiaodich
     */
    public Quanlygiaodich() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jf_magiaodich = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jf_ngaygiaodich = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jf_dongia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jf_soluong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jf_loaigiaodich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jf_loaivang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jf_tigia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ja_hienthi = new javax.swing.JTextArea();
        b_exit = new javax.swing.JButton();
        b_save = new javax.swing.JButton();
        b_xemvang = new javax.swing.JButton();
        b_xemtiente = new javax.swing.JButton();
        b_soluongvang = new javax.swing.JButton();
        b_soluongtiente = new javax.swing.JButton();
        b_trungbinhtiente = new javax.swing.JButton();
        b_donhang1ty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã giao dịch:");

        jLabel2.setText("Ngày giao dịch:");

        jLabel3.setText("Đơn giá:");

        jLabel4.setText("Số lượng:");

        jLabel5.setText("Loại giao dịch:");

        jLabel6.setText("Loại vàng:");

        jLabel7.setText("Tỉ giá:");

        jf_tigia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_tigiaActionPerformed(evt);
            }
        });

        ja_hienthi.setColumns(20);
        ja_hienthi.setRows(5);
        jScrollPane1.setViewportView(ja_hienthi);

        b_exit.setText("Exit");
        b_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_exitActionPerformed(evt);
            }
        });

        b_save.setText("Save");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        b_xemvang.setText("Xem giao dịch vàng");
        b_xemvang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemvangActionPerformed(evt);
            }
        });

        b_xemtiente.setText("Xem giao dịch tiền tệ");
        b_xemtiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemtienteActionPerformed(evt);
            }
        });

        b_soluongvang.setText("Số lượng giao dịch vàng");
        b_soluongvang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_soluongvangActionPerformed(evt);
            }
        });

        b_soluongtiente.setText("Số lượng giao dịch tiền tệ");
        b_soluongtiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_soluongtienteActionPerformed(evt);
            }
        });

        b_trungbinhtiente.setText("Trung bình tiền giao dịch tiền tệ");
        b_trungbinhtiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_trungbinhtienteActionPerformed(evt);
            }
        });

        b_donhang1ty.setText("Đơn hàng trên 1 tỷ");
        b_donhang1ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_donhang1tyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jf_tigia, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jf_magiaodich)
                            .addComponent(jf_dongia)
                            .addComponent(jf_loaigiaodich))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jf_loaivang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jf_soluong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jf_ngaygiaodich, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b_trungbinhtiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_soluongtiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_soluongvang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_xemtiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_xemvang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_exit))
                            .addComponent(b_donhang1ty, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jf_magiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jf_ngaygiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jf_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jf_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jf_loaigiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jf_tigia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jf_loaivang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_exit)
                    .addComponent(b_save)
                    .addComponent(b_xemvang)
                    .addComponent(b_xemtiente)
                    .addComponent(b_soluongvang)
                    .addComponent(b_soluongtiente)
                    .addComponent(b_trungbinhtiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_donhang1ty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jf_tigiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_tigiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_tigiaActionPerformed

    private void b_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_exitActionPerformed

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
        int mgd=Integer.parseInt(this.jf_magiaodich.getText());
        String ngd=this.jf_ngaygiaodich.getText();
        double dg=Double.parseDouble(this.jf_dongia.getText());
        int sl=Integer.parseInt(this.jf_soluong.getText());
        String lv=this.jf_loaivang.getText();
        double tg=Double.parseDouble(this.jf_tigia.getText());
        int lgd=Integer.parseInt(this.jf_loaigiaodich.getText());
        if (lgd==1)
        {
            Vang v=new Vang (lv,mgd,sl,dg,ngd);
            listVang.add(v);
        }
        else
        {
            Tiente tt= new Tiente (tg,mgd,sl,dg,ngd);
            listTiente.add(tt);
        }
        
    }//GEN-LAST:event_b_saveActionPerformed

    private void b_xemvangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemvangActionPerformed
        // TODO add your handling code here:
        for (Vang v:listVang)
        {
            this.ja_hienthi.append("\n|\t\t"+v.getMagd()+"|\t\t"+v.getNgaygd()+"|\t\t"+v.getDongia()+"|\t\t"+v.getSoluong()+"|\t\t"+v.getLoaivang()+"|\t\t"+v.getThanhtien()+"|");
        }
    }//GEN-LAST:event_b_xemvangActionPerformed

    private void b_xemtienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemtienteActionPerformed
        // TODO add your handling code here:
        for (Tiente tt:listTiente)
        {
            this.ja_hienthi.append("\n|\t\t"+tt.getMagd()+"|\t\t"+tt.getNgaygd()+"|\t\t"+tt.getDongia()+"|\t\t"+tt.getSoluong()+"|\t\t"+tt.getTigia()+"|\t\t"+tt.getThanhtien()+"|");
        }
    }//GEN-LAST:event_b_xemtienteActionPerformed

    private void b_soluongvangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_soluongvangActionPerformed
        // TODO add your handling code here:
        int i,sum=0;
        
        for (i=0;i<listVang.size();i++)
        {
            sum+=listVang.get(i).getSoluong();
        }
        this.ja_hienthi.append("\nTổng số lượng vàng trong giao dịch vàng: "+sum);
    }//GEN-LAST:event_b_soluongvangActionPerformed

    private void b_soluongtienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_soluongtienteActionPerformed
        // TODO add your handling code here:
        int i,sum=0;
        
        for (i=0;i<listTiente.size();i++)
        {
            sum+=listTiente.get(i).getSoluong();
        }
        this.ja_hienthi.append("\nTổng số lượng tiền tệ trong giao dịch tiền tệ: "+sum);
    }//GEN-LAST:event_b_soluongtienteActionPerformed

    private void b_trungbinhtienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_trungbinhtienteActionPerformed
        // TODO add your handling code here:
        int i;
        double sum=0,avg;
        for (i=0;i<listTiente.size();i++)
        {
            sum+=listTiente.get(i).getThanhtien();
        }
        avg=sum/listTiente.size();
        this.ja_hienthi.append("\nTrung bình tiền tệ của giao dịch tiền tệ: "+avg);
    }//GEN-LAST:event_b_trungbinhtienteActionPerformed

    private void b_donhang1tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_donhang1tyActionPerformed
        // TODO add your handling code here:
        for (Vang v: listVang)
        {
            if (v.getDongia()>1000000000)
                this.ja_hienthi.append("\n|\t\t"+v.getMagd()+"|\t\t"+v.getNgaygd()+"|\t\t"+v.getDongia()+"|\t\t"+v.getSoluong()+"|\t\t"+v.getLoaivang()+"|\t\t"+v.getThanhtien()+"|");
        }
        for (Tiente tt: listTiente)
        {
            if (tt.getDongia()>1000000000)
                this.ja_hienthi.append("\n|\t\t"+tt.getMagd()+"|\t\t"+tt.getNgaygd()+"|\t\t"+tt.getDongia()+"|\t\t"+tt.getSoluong()+"|\t\t"+tt.getTigia()+"|\t\t"+tt.getThanhtien()+"|");
        }
    }//GEN-LAST:event_b_donhang1tyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlygiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlygiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlygiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlygiaodich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlygiaodich().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_donhang1ty;
    private javax.swing.JButton b_exit;
    private javax.swing.JButton b_save;
    private javax.swing.JButton b_soluongtiente;
    private javax.swing.JButton b_soluongvang;
    private javax.swing.JButton b_trungbinhtiente;
    private javax.swing.JButton b_xemtiente;
    private javax.swing.JButton b_xemvang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ja_hienthi;
    private javax.swing.JTextField jf_dongia;
    private javax.swing.JTextField jf_loaigiaodich;
    private javax.swing.JTextField jf_loaivang;
    private javax.swing.JTextField jf_magiaodich;
    private javax.swing.JTextField jf_ngaygiaodich;
    private javax.swing.JTextField jf_soluong;
    private javax.swing.JTextField jf_tigia;
    // End of variables declaration//GEN-END:variables
}
