/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai1;

import java.util.ArrayList;

/**
 *
 * @author ASM
 */
public class Quanlytuyenxe extends javax.swing.JFrame {
    private ArrayList<Xenoi> listXenoi=new ArrayList();
    private ArrayList<Xengoai> listXengoai=new ArrayList();
    Manager m= new Manager ();
    /**
     * Creates new form Quanlytuyenxe
     */
    public Quanlytuyenxe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_machuyen = new javax.swing.JTextField();
        tf_taixe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_soxe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_doanhthu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_loaixe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_sotuyen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_noiden = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_sokmdi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_songaydi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_hienthi = new javax.swing.JTextArea();
        b_thoat = new javax.swing.JButton();
        b_themxe = new javax.swing.JButton();
        b_xemxenoi = new javax.swing.JButton();
        b_xengoaithanh = new javax.swing.JButton();
        b_sumdoanhthuxenoi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã chuyến:");

        tf_machuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_machuyenActionPerformed(evt);
            }
        });

        tf_taixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_taixeActionPerformed(evt);
            }
        });

        jLabel2.setText("Tài xế:");

        tf_soxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_soxeActionPerformed(evt);
            }
        });

        jLabel3.setText("Số xe:");

        tf_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_doanhthuActionPerformed(evt);
            }
        });

        jLabel4.setText("Doanh thu:");

        tf_loaixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_loaixeActionPerformed(evt);
            }
        });

        jLabel5.setText("Loại xe:");

        tf_sotuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sotuyenActionPerformed(evt);
            }
        });

        jLabel6.setText("Số tuyến:");

        tf_noiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_noidenActionPerformed(evt);
            }
        });

        jLabel7.setText("Nơi đến:");

        tf_sokmdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sokmdiActionPerformed(evt);
            }
        });

        jLabel8.setText("Số km đi:");

        tf_songaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_songaydiActionPerformed(evt);
            }
        });

        jLabel9.setText("Số ngay đi:");

        ta_hienthi.setColumns(20);
        ta_hienthi.setRows(5);
        jScrollPane1.setViewportView(ta_hienthi);

        b_thoat.setText("Exit");
        b_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_thoatActionPerformed(evt);
            }
        });

        b_themxe.setText("Save");
        b_themxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themxeActionPerformed(evt);
            }
        });

        b_xemxenoi.setText("Xe nội thành");
        b_xemxenoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemxenoiActionPerformed(evt);
            }
        });

        b_xengoaithanh.setText("Xe ngoại thành");
        b_xengoaithanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xengoaithanhActionPerformed(evt);
            }
        });

        b_sumdoanhthuxenoi.setText("Tổng doanh thu xe nội");
        b_sumdoanhthuxenoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sumdoanhthuxenoiActionPerformed(evt);
            }
        });

        jButton2.setText("Tổng doanh thu xe ngoại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sokmdi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_taixe, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_noiden, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_songaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(b_sumdoanhthuxenoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_xengoaithanh, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_xemxenoi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_themxe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tf_taixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_noiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_sokmdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_songaydi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_thoat)
                    .addComponent(b_themxe)
                    .addComponent(b_xemxenoi)
                    .addComponent(b_xengoaithanh)
                    .addComponent(b_sumdoanhthuxenoi)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_machuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_machuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_machuyenActionPerformed

    private void tf_taixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_taixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_taixeActionPerformed

    private void tf_soxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_soxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_soxeActionPerformed

    private void tf_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_doanhthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_doanhthuActionPerformed

    private void tf_loaixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_loaixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_loaixeActionPerformed

    private void tf_sotuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sotuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sotuyenActionPerformed

    private void tf_noidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_noidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_noidenActionPerformed

    private void tf_sokmdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sokmdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sokmdiActionPerformed

    private void tf_songaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_songaydiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_songaydiActionPerformed

    private void b_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_thoatActionPerformed

    private void b_themxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themxeActionPerformed
        // TODO add your handling code here:
        String mc=this.tf_machuyen.getText();
        String tx=this.tf_taixe.getText();
        String sx=this.tf_soxe.getText();
        double dt=Double.parseDouble(this.tf_doanhthu.getText());
        int lx=Integer.parseInt(this.tf_loaixe.getText());
        int st=Integer.parseInt(this.tf_sotuyen.getText());
        String nd=this.tf_noiden.getText();
        double skd=Double.parseDouble(this.tf_sokmdi.getText());
        int snd=Integer.parseInt(this.tf_songaydi.getText());
        if (lx==1)
        {
            Xenoi noi=new Xenoi (mc,tx,sx,dt,st,skd);
            listXenoi.add(noi);
        }
        else
        {
            Xengoai ngoai= new Xengoai (mc,tx,sx,dt,nd,snd);
            listXengoai.add(ngoai);
        }
        
    }//GEN-LAST:event_b_themxeActionPerformed

    private void b_xemxenoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemxenoiActionPerformed
        // TODO add your handling code here:
        for (Xenoi noi: listXenoi)
        {
            this.ta_hienthi.setText(noi.toString());
        }
    }//GEN-LAST:event_b_xemxenoiActionPerformed

    private void b_xengoaithanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xengoaithanhActionPerformed
        // TODO add your handling code here:
         for(Xengoai ngoai: listXengoai)
         {
             this.ta_hienthi.setText(ngoai.toString());
         }
    }//GEN-LAST:event_b_xengoaithanhActionPerformed

    private void b_sumdoanhthuxenoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sumdoanhthuxenoiActionPerformed
        // TODO add your handling code here:
        this.ta_hienthi.append("Tổng doanh thu xe nội: "+m.sumDoanhthuxenoi());
    }//GEN-LAST:event_b_sumdoanhthuxenoiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.ta_hienthi.append("Tổng doanh thu xe ngoại: "+m.sumDoanhthuxengoai());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlytuyenxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlytuyenxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlytuyenxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlytuyenxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlytuyenxe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_sumdoanhthuxenoi;
    private javax.swing.JButton b_themxe;
    private javax.swing.JButton b_thoat;
    private javax.swing.JButton b_xemxenoi;
    private javax.swing.JButton b_xengoaithanh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_hienthi;
    private javax.swing.JTextField tf_doanhthu;
    private javax.swing.JTextField tf_loaixe;
    private javax.swing.JTextField tf_machuyen;
    private javax.swing.JTextField tf_noiden;
    private javax.swing.JTextField tf_sokmdi;
    private javax.swing.JTextField tf_songaydi;
    private javax.swing.JTextField tf_sotuyen;
    private javax.swing.JTextField tf_soxe;
    private javax.swing.JTextField tf_taixe;
    // End of variables declaration//GEN-END:variables
}
