/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De1;

/**
 *
 * @author ASM
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import java.util.ArrayList;
public class Form extends javax.swing.JFrame {
    ArrayList<Student> listStudent=new ArrayList<>();
    private Student s=new Student();

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jf_hoten = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ja_hienthi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jf_ngaysinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jf_diachi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jf_diemtongket = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jf_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jf_masinhvien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jf_gioitinh = new javax.swing.JTextField();
        b_luudanhsachsinhvien = new javax.swing.JButton();
        b_xemdanhsachsinhvien = new javax.swing.JButton();
        b_themsinhvien = new javax.swing.JButton();
        b_exit = new javax.swing.JButton();
        b_xem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Form cho sinh viên");

        jLabel2.setText("Họ và tên:");

        ja_hienthi.setColumns(20);
        ja_hienthi.setRows(5);
        jScrollPane2.setViewportView(ja_hienthi);

        jLabel3.setText("Ngày Sinh:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Điểm tổng kết:");

        jLabel6.setText("Email:");

        jLabel7.setText("Mã sinh viên:");

        jLabel8.setText("Giới tính: ");

        b_luudanhsachsinhvien.setText("Lưu danh sách sinh viên");
        b_luudanhsachsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_luudanhsachsinhvienActionPerformed(evt);
            }
        });

        b_xemdanhsachsinhvien.setText("Mở danh sách sinh viên");
        b_xemdanhsachsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemdanhsachsinhvienActionPerformed(evt);
            }
        });

        b_themsinhvien.setText("Thêm sinh viên");
        b_themsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_themsinhvienActionPerformed(evt);
            }
        });

        b_exit.setText("Exit");
        b_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_exitActionPerformed(evt);
            }
        });

        b_xem.setText("Xem");
        b_xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jf_hoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jf_masinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(659, 659, 659))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jf_gioitinh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(jf_diachi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_diemtongket, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(659, 659, 659))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_luudanhsachsinhvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_xemdanhsachsinhvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_themsinhvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_xem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_exit)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jf_masinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jf_diemtongket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_luudanhsachsinhvien)
                    .addComponent(b_xemdanhsachsinhvien)
                    .addComponent(b_themsinhvien)
                    .addComponent(b_exit)
                    .addComponent(b_xem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_exitActionPerformed

    private void b_themsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_themsinhvienActionPerformed
        // TODO add your handling code here:
        try {
            String a=jf_hoten.getText();
        String b=jf_ngaysinh.getText();
        String c=jf_diachi.getText();
        String d=jf_gioitinh.getText();
        String e=jf_masinhvien.getText();
        String f=jf_email.getText();
        double g=Double.parseDouble(jf_diemtongket.getText());
        Student s=new Student(a, b, c, d, e, f, g);
        JOptionPane.showMessageDialog(null,"Thêm sinh viên thành công.");
        listStudent.add(s);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Không thêm được sinh viên");
        }
    }//GEN-LAST:event_b_themsinhvienActionPerformed

    private void b_luudanhsachsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_luudanhsachsinhvienActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos=new FileOutputStream("sinhvien.dat");
            ObjectOutputStream oos=new ObjectOutputStream(fos);
            oos.writeObject(listStudent);
            JOptionPane.showMessageDialog(null,"Lưu file thành công");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Không lưu được file.");
        }
        
    }//GEN-LAST:event_b_luudanhsachsinhvienActionPerformed

    private void b_xemdanhsachsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemdanhsachsinhvienActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis=new FileInputStream("sinhvien.dat");
            ObjectInputStream ois=new ObjectInputStream(fis);
            listStudent=(ArrayList<Student>)ois.readObject();;
            ois.close();
        } catch (Exception e) {
            e.printStackTrace();//JOptionPane.showMessageDialog(null,"IO Error");
        }
        for(Student s:listStudent)
        ja_hienthi.append(s.toString());
    }//GEN-LAST:event_b_xemdanhsachsinhvienActionPerformed

    private void b_xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xemActionPerformed
        // TODO add your handling code here:
        for(Student s:listStudent)
            this.ja_hienthi.append(s.toString());
    }//GEN-LAST:event_b_xemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_exit;
    private javax.swing.JButton b_luudanhsachsinhvien;
    private javax.swing.JButton b_themsinhvien;
    private javax.swing.JButton b_xem;
    private javax.swing.JButton b_xemdanhsachsinhvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ja_hienthi;
    private javax.swing.JTextField jf_diachi;
    private javax.swing.JTextField jf_diemtongket;
    private javax.swing.JTextField jf_email;
    private javax.swing.JTextField jf_gioitinh;
    private javax.swing.JTextField jf_hoten;
    private javax.swing.JTextField jf_masinhvien;
    private javax.swing.JTextField jf_ngaysinh;
    // End of variables declaration//GEN-END:variables
}
